### ISSUE TITLE
Abstracción

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-los_otros#5]
Esta forma de generar valores...
https://github.com/aigora/twE105_1920-los_otros/blob/dd8fc47408e70fcba530f19d08f189164ad8112b/Programa/Domino.c#L9-L13
...es artesanal, uno a uno. Debéis hacer un ejercicio de abstracción, mediante una fórmula o similar que os permita rellenar el vector de contenido de manera elegante y flexible.

**Comment by oscarperpinan** [comment]
Pasa lo mismo aquí: 
https://github.com/aigora/twE105_1920-los_otros/blob/dd8fc47408e70fcba530f19d08f189164ad8112b/Programa/Domino.c#L82
Estáis repitiendo el código una y otra vez para hacer lo mismo, con mínimos cambios para adaptaros al número de jugadores. 
Recordad: [Don't Repeat Yourself](https://www.oreilly.com/library/view/97-things-every/9780596809515/ch30.html)

**Comment by GilCarvalho55175** [comment]
sería posible implementar punteros que usen las fichas de los jugadores que no van a participar como parte del pozo? así solohabría que repartir una vez sin mirar el numero de jugadores

**Comment by oscarperpinan** [comment]
Sí, es una posible solución

**Comment by sergio-dp** [comment]
Ya he modificado ambas recomendaciones. ¿Así está bien o intento hacerlo de otra forma?

**Comment by oscarperpinan** [comment]
Disculpad, no había visto este mensaje.

Me lo marco para revisar.

**Comment by oscarperpinan** [comment]
Revisado. Mucho mejor así.
